//
// Generated file, do not edit! Created by nedtool 5.4 from messages/CCQuery.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __CCQUERY_M_H
#define __CCQUERY_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "../common/Constants.h"
// }}

/**
 * Class generated from <tt>messages/CCQuery.msg:24</tt> by nedtool.
 * <pre>
 * packet CCQuery
 * {
 *     string displayString = DISPLAY_STR_MSG_GROUP_CC;
 * 
 *     string candidate;
 * }
 * </pre>
 */
class CCQuery : public ::omnetpp::cPacket
{
  protected:
    ::omnetpp::opp_string displayString;
    ::omnetpp::opp_string candidate;

  private:
    void copy(const CCQuery& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const CCQuery&);

  public:
    CCQuery(const char *name=nullptr, short kind=0);
    CCQuery(const CCQuery& other);
    virtual ~CCQuery();
    CCQuery& operator=(const CCQuery& other);
    virtual CCQuery *dup() const override {return new CCQuery(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getDisplayString() const;
    virtual void setDisplayString(const char * displayString);
    virtual const char * getCandidate() const;
    virtual void setCandidate(const char * candidate);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CCQuery& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CCQuery& obj) {obj.parsimUnpack(b);}


#endif // ifndef __CCQUERY_M_H

