//
// Generated file, do not edit! Created by nedtool 5.5 from messages/ClientData.msg.
//

#ifndef __CLIENTDATA_M_H
#define __CLIENTDATA_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "../common/Constants.h"
// }}

/**
 * Class generated from <tt>messages/ClientData.msg:20</tt> by nedtool.
 * <pre>
 * packet ClientData
 * {
 *     string content;
 *     int size;
 * }
 * </pre>
 */
class ClientData : public ::omnetpp::cPacket
{
  protected:
    ::omnetpp::opp_string content;
    int size;

  private:
    void copy(const ClientData& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ClientData&);

  public:
    ClientData(const char *name=nullptr, short kind=0);
    ClientData(const ClientData& other);
    virtual ~ClientData();
    ClientData& operator=(const ClientData& other);
    virtual ClientData *dup() const override {return new ClientData(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getContent() const;
    virtual void setContent(const char * content);
    virtual int getSize() const;
    virtual void setSize(int size);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ClientData& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ClientData& obj) {obj.parsimUnpack(b);}


#endif // ifndef __CLIENTDATA_M_H

