//
// Generated file, do not edit! Created by nedtool 5.4 from messages/ConnectReply.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __CONNECTREPLY_M_H
#define __CONNECTREPLY_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>messages/ConnectReply.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet ConnectReply
 * {
 *     string LCName;
 *     string hostAddrs;
 * }
 * </pre>
 */
class ConnectReply : public ::omnetpp::cPacket
{
  protected:
    ::omnetpp::opp_string LCName;
    ::omnetpp::opp_string hostAddrs;

  private:
    void copy(const ConnectReply& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ConnectReply&);

  public:
    ConnectReply(const char *name=nullptr, short kind=0);
    ConnectReply(const ConnectReply& other);
    virtual ~ConnectReply();
    ConnectReply& operator=(const ConnectReply& other);
    virtual ConnectReply *dup() const override {return new ConnectReply(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getLCName() const;
    virtual void setLCName(const char * LCName);
    virtual const char * getHostAddrs() const;
    virtual void setHostAddrs(const char * hostAddrs);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ConnectReply& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ConnectReply& obj) {obj.parsimUnpack(b);}


#endif // ifndef __CONNECTREPLY_M_H

