//
// Generated file, do not edit! Created by nedtool 5.4 from messages/ConsensusNAck.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __CONSENSUSNACK_M_H
#define __CONSENSUSNACK_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "../common/Constants.h"
// }}

/**
 * Class generated from <tt>messages/ConsensusNAck.msg:21</tt> by nedtool.
 * <pre>
 * packet ConsensusNAck
 * {
 *     string displayString = DISPLAY_STR_MSG_GROUP_EH;
 *     int epoch;
 *     int groupId;
 *     int round;
 *     string senderName;
 * }
 * </pre>
 */
class ConsensusNAck : public ::omnetpp::cPacket
{
  protected:
    ::omnetpp::opp_string displayString;
    int epoch;
    int groupId;
    int round;
    ::omnetpp::opp_string senderName;

  private:
    void copy(const ConsensusNAck& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ConsensusNAck&);

  public:
    ConsensusNAck(const char *name=nullptr, short kind=0);
    ConsensusNAck(const ConsensusNAck& other);
    virtual ~ConsensusNAck();
    ConsensusNAck& operator=(const ConsensusNAck& other);
    virtual ConsensusNAck *dup() const override {return new ConsensusNAck(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getDisplayString() const;
    virtual void setDisplayString(const char * displayString);
    virtual int getEpoch() const;
    virtual void setEpoch(int epoch);
    virtual int getGroupId() const;
    virtual void setGroupId(int groupId);
    virtual int getRound() const;
    virtual void setRound(int round);
    virtual const char * getSenderName() const;
    virtual void setSenderName(const char * senderName);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ConsensusNAck& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ConsensusNAck& obj) {obj.parsimUnpack(b);}


#endif // ifndef __CONSENSUSNACK_M_H

