//
// Generated file, do not edit! Created by nedtool 5.4 from messages/ConsensusQuery.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __CONSENSUSQUERY_M_H
#define __CONSENSUSQUERY_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "../common/Constants.h"
// }}

/**
 * Class generated from <tt>messages/ConsensusQuery.msg:24</tt> by nedtool.
 * <pre>
 * packet ConsensusQuery
 * {
 *     string displayString = DISPLAY_STR_MSG_GROUP_EH;
 * 
 *     string senderName;
 *     int epoch;
 *     int groupId;
 *     int round;
 *     string seqRanges;
 * }
 * </pre>
 */
class ConsensusQuery : public ::omnetpp::cPacket
{
  protected:
    ::omnetpp::opp_string displayString;
    ::omnetpp::opp_string senderName;
    int epoch;
    int groupId;
    int round;
    ::omnetpp::opp_string seqRanges;

  private:
    void copy(const ConsensusQuery& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ConsensusQuery&);

  public:
    ConsensusQuery(const char *name=nullptr, short kind=0);
    ConsensusQuery(const ConsensusQuery& other);
    virtual ~ConsensusQuery();
    ConsensusQuery& operator=(const ConsensusQuery& other);
    virtual ConsensusQuery *dup() const override {return new ConsensusQuery(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getDisplayString() const;
    virtual void setDisplayString(const char * displayString);
    virtual const char * getSenderName() const;
    virtual void setSenderName(const char * senderName);
    virtual int getEpoch() const;
    virtual void setEpoch(int epoch);
    virtual int getGroupId() const;
    virtual void setGroupId(int groupId);
    virtual int getRound() const;
    virtual void setRound(int round);
    virtual const char * getSeqRanges() const;
    virtual void setSeqRanges(const char * seqRanges);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ConsensusQuery& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ConsensusQuery& obj) {obj.parsimUnpack(b);}


#endif // ifndef __CONSENSUSQUERY_M_H

