//
// Generated file, do not edit! Created by nedtool 5.4 from messages/CycleEvent.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __CYCLEEVENT_M_H
#define __CYCLEEVENT_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "../common/Constants.h"
// }}

/**
 * Class generated from <tt>messages/CycleEvent.msg:24</tt> by nedtool.
 * <pre>
 * packet CycleEvent
 * {
 *     string displayString = DISPLAY_STR_MSG_GROUP_CC;
 * 
 *     string senderName;
 *     int round;
 *     string cycleEvents;
 * }
 * </pre>
 */
class CycleEvent : public ::omnetpp::cPacket
{
  protected:
    ::omnetpp::opp_string displayString;
    ::omnetpp::opp_string senderName;
    int round;
    ::omnetpp::opp_string cycleEvents;

  private:
    void copy(const CycleEvent& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const CycleEvent&);

  public:
    CycleEvent(const char *name=nullptr, short kind=0);
    CycleEvent(const CycleEvent& other);
    virtual ~CycleEvent();
    CycleEvent& operator=(const CycleEvent& other);
    virtual CycleEvent *dup() const override {return new CycleEvent(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getDisplayString() const;
    virtual void setDisplayString(const char * displayString);
    virtual const char * getSenderName() const;
    virtual void setSenderName(const char * senderName);
    virtual int getRound() const;
    virtual void setRound(int round);
    virtual const char * getCycleEvents() const;
    virtual void setCycleEvents(const char * cycleEvents);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CycleEvent& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CycleEvent& obj) {obj.parsimUnpack(b);}


#endif // ifndef __CYCLEEVENT_M_H

