//
// Generated file, do not edit! Created by nedtool 5.4 from messages/Decision.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __DECISION_M_H
#define __DECISION_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "../common/Constants.h"
// }}

/**
 * Class generated from <tt>messages/Decision.msg:24</tt> by nedtool.
 * <pre>
 * packet Decision
 * {
 *     string displayString = DISPLAY_STR_MSG_GROUP_EH;
 * 
 *     string senderName;
 *     int round;
 *     int epoch;
 *     int groupId;
 *     string decision;
 * }
 * </pre>
 */
class Decision : public ::omnetpp::cPacket
{
  protected:
    ::omnetpp::opp_string displayString;
    ::omnetpp::opp_string senderName;
    int round;
    int epoch;
    int groupId;
    ::omnetpp::opp_string decision;

  private:
    void copy(const Decision& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Decision&);

  public:
    Decision(const char *name=nullptr, short kind=0);
    Decision(const Decision& other);
    virtual ~Decision();
    Decision& operator=(const Decision& other);
    virtual Decision *dup() const override {return new Decision(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getDisplayString() const;
    virtual void setDisplayString(const char * displayString);
    virtual const char * getSenderName() const;
    virtual void setSenderName(const char * senderName);
    virtual int getRound() const;
    virtual void setRound(int round);
    virtual int getEpoch() const;
    virtual void setEpoch(int epoch);
    virtual int getGroupId() const;
    virtual void setGroupId(int groupId);
    virtual const char * getDecision() const;
    virtual void setDecision(const char * decision);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Decision& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Decision& obj) {obj.parsimUnpack(b);}


#endif // ifndef __DECISION_M_H

