//
// Generated file, do not edit! Created by nedtool 5.4 from messages/Event.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __EVENT_M_H
#define __EVENT_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "../common/Constants.h"
// }}

/**
 * Class generated from <tt>messages/Event.msg:20</tt> by nedtool.
 * <pre>
 * packet Event
 * {
 *     unsigned long senderId;
 *     int seq;
 *     string content;
 * 
 *     // sourceName and destName must be set for module purge
 *     string sourceName;
 *     string destName;
 * }
 * </pre>
 */
class Event : public ::omnetpp::cPacket
{
  protected:
    unsigned long senderId;
    int seq;
    ::omnetpp::opp_string content;
    ::omnetpp::opp_string sourceName;
    ::omnetpp::opp_string destName;

  private:
    void copy(const Event& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Event&);

  public:
    Event(const char *name=nullptr, short kind=0);
    Event(const Event& other);
    virtual ~Event();
    Event& operator=(const Event& other);
    virtual Event *dup() const override {return new Event(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual unsigned long getSenderId() const;
    virtual void setSenderId(unsigned long senderId);
    virtual int getSeq() const;
    virtual void setSeq(int seq);
    virtual const char * getContent() const;
    virtual void setContent(const char * content);
    virtual const char * getSourceName() const;
    virtual void setSourceName(const char * sourceName);
    virtual const char * getDestName() const;
    virtual void setDestName(const char * destName);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Event& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Event& obj) {obj.parsimUnpack(b);}


#endif // ifndef __EVENT_M_H

