//
// Generated file, do not edit! Created by nedtool 5.4 from messages/Failure.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __FAILURE_M_H
#define __FAILURE_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>messages/Failure.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet Failure
 * {
 *     string hostAddress;
 * }
 * </pre>
 */
class Failure : public ::omnetpp::cPacket
{
  protected:
    ::omnetpp::opp_string hostAddress;

  private:
    void copy(const Failure& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Failure&);

  public:
    Failure(const char *name=nullptr, short kind=0);
    Failure(const Failure& other);
    virtual ~Failure();
    Failure& operator=(const Failure& other);
    virtual Failure *dup() const override {return new Failure(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getHostAddress() const;
    virtual void setHostAddress(const char * hostAddress);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Failure& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Failure& obj) {obj.parsimUnpack(b);}


#endif // ifndef __FAILURE_M_H

