//
// Generated file, do not edit! Created by nedtool 5.4 from messages/Final.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __FINAL_M_H
#define __FINAL_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "../common/Constants.h"
// }}

/**
 * Class generated from <tt>messages/Final.msg:24</tt> by nedtool.
 * <pre>
 * packet Final
 * {
 *     string displayString = DISPLAY_STR_MSG_GROUP_EH;
 * 
 *     string senderName;
 *     int epoch;
 *     int groupId;
 *     int round;
 * }
 * </pre>
 */
class Final : public ::omnetpp::cPacket
{
  protected:
    ::omnetpp::opp_string displayString;
    ::omnetpp::opp_string senderName;
    int epoch;
    int groupId;
    int round;

  private:
    void copy(const Final& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Final&);

  public:
    Final(const char *name=nullptr, short kind=0);
    Final(const Final& other);
    virtual ~Final();
    Final& operator=(const Final& other);
    virtual Final *dup() const override {return new Final(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getDisplayString() const;
    virtual void setDisplayString(const char * displayString);
    virtual const char * getSenderName() const;
    virtual void setSenderName(const char * senderName);
    virtual int getEpoch() const;
    virtual void setEpoch(int epoch);
    virtual int getGroupId() const;
    virtual void setGroupId(int groupId);
    virtual int getRound() const;
    virtual void setRound(int round);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Final& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Final& obj) {obj.parsimUnpack(b);}


#endif // ifndef __FINAL_M_H

