//
// Generated file, do not edit! Created by nedtool 5.4 from messages/GRNAck.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __GRNACK_M_H
#define __GRNACK_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "../common/Constants.h"
// }}

/**
 * Class generated from <tt>messages/GRNAck.msg:20</tt> by nedtool.
 * <pre>
 * packet GRNAck
 * {
 *     string displayString = DISPLAY_STR_MSG_GROUP_CC;
 * 
 *     string senderName;
 *     int gidTemp;
 * }
 * </pre>
 */
class GRNAck : public ::omnetpp::cPacket
{
  protected:
    ::omnetpp::opp_string displayString;
    ::omnetpp::opp_string senderName;
    int gidTemp;

  private:
    void copy(const GRNAck& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const GRNAck&);

  public:
    GRNAck(const char *name=nullptr, short kind=0);
    GRNAck(const GRNAck& other);
    virtual ~GRNAck();
    GRNAck& operator=(const GRNAck& other);
    virtual GRNAck *dup() const override {return new GRNAck(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getDisplayString() const;
    virtual void setDisplayString(const char * displayString);
    virtual const char * getSenderName() const;
    virtual void setSenderName(const char * senderName);
    virtual int getGidTemp() const;
    virtual void setGidTemp(int gidTemp);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const GRNAck& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, GRNAck& obj) {obj.parsimUnpack(b);}


#endif // ifndef __GRNACK_M_H

