//
// Generated file, do not edit! Created by nedtool 5.4 from messages/GRQuery.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __GRQUERY_M_H
#define __GRQUERY_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "../common/Constants.h"
// }}

/**
 * Class generated from <tt>messages/GRQuery.msg:24</tt> by nedtool.
 * <pre>
 * packet GRQuery
 * {
 *     string displayString = DISPLAY_STR_MSG_GROUP_GR;
 * 
 *     string senderName;
 *     int epoch;
 *     int groupId;
 * }
 * </pre>
 */
class GRQuery : public ::omnetpp::cPacket
{
  protected:
    ::omnetpp::opp_string displayString;
    ::omnetpp::opp_string senderName;
    int epoch;
    int groupId;

  private:
    void copy(const GRQuery& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const GRQuery&);

  public:
    GRQuery(const char *name=nullptr, short kind=0);
    GRQuery(const GRQuery& other);
    virtual ~GRQuery();
    GRQuery& operator=(const GRQuery& other);
    virtual GRQuery *dup() const override {return new GRQuery(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getDisplayString() const;
    virtual void setDisplayString(const char * displayString);
    virtual const char * getSenderName() const;
    virtual void setSenderName(const char * senderName);
    virtual int getEpoch() const;
    virtual void setEpoch(int epoch);
    virtual int getGroupId() const;
    virtual void setGroupId(int groupId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const GRQuery& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, GRQuery& obj) {obj.parsimUnpack(b);}


#endif // ifndef __GRQUERY_M_H

