//
// Generated file, do not edit! Created by nedtool 5.4 from messages/GRSilent.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __GRSILENT_M_H
#define __GRSILENT_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "../common/Constants.h"
// }}

/**
 * Class generated from <tt>messages/GRSilent.msg:24</tt> by nedtool.
 * <pre>
 * packet GRSilent
 * {
 *     string displayString = DISPLAY_STR_MSG_GROUP_GR;
 * 
 *     string senderName;
 *     int epoch;
 *     int groupId;
 *     string memberList;
 * }
 * </pre>
 */
class GRSilent : public ::omnetpp::cPacket
{
  protected:
    ::omnetpp::opp_string displayString;
    ::omnetpp::opp_string senderName;
    int epoch;
    int groupId;
    ::omnetpp::opp_string memberList;

  private:
    void copy(const GRSilent& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const GRSilent&);

  public:
    GRSilent(const char *name=nullptr, short kind=0);
    GRSilent(const GRSilent& other);
    virtual ~GRSilent();
    GRSilent& operator=(const GRSilent& other);
    virtual GRSilent *dup() const override {return new GRSilent(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getDisplayString() const;
    virtual void setDisplayString(const char * displayString);
    virtual const char * getSenderName() const;
    virtual void setSenderName(const char * senderName);
    virtual int getEpoch() const;
    virtual void setEpoch(int epoch);
    virtual int getGroupId() const;
    virtual void setGroupId(int groupId);
    virtual const char * getMemberList() const;
    virtual void setMemberList(const char * memberList);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const GRSilent& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, GRSilent& obj) {obj.parsimUnpack(b);}


#endif // ifndef __GRSILENT_M_H

