//
// Generated file, do not edit! Created by nedtool 5.4 from messages/HandShakeReject.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __HANDSHAKEREJECT_M_H
#define __HANDSHAKEREJECT_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>messages/HandShakeReject.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet HandShakeReject
 * {
 *     string LCName;
 *     string hostAddrs;
 * }
 * </pre>
 */
class HandShakeReject : public ::omnetpp::cPacket
{
  protected:
    ::omnetpp::opp_string LCName;
    ::omnetpp::opp_string hostAddrs;

  private:
    void copy(const HandShakeReject& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const HandShakeReject&);

  public:
    HandShakeReject(const char *name=nullptr, short kind=0);
    HandShakeReject(const HandShakeReject& other);
    virtual ~HandShakeReject();
    HandShakeReject& operator=(const HandShakeReject& other);
    virtual HandShakeReject *dup() const override {return new HandShakeReject(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getLCName() const;
    virtual void setLCName(const char * LCName);
    virtual const char * getHostAddrs() const;
    virtual void setHostAddrs(const char * hostAddrs);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const HandShakeReject& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, HandShakeReject& obj) {obj.parsimUnpack(b);}


#endif // ifndef __HANDSHAKEREJECT_M_H

