//
// Generated file, do not edit! Created by nedtool 5.4 from messages/HandShakeTimeout.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __HANDSHAKETIMEOUT_M_H
#define __HANDSHAKETIMEOUT_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>messages/HandShakeTimeout.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet HandShakeTimeout
 * {
 *     string LCName;
 * }
 * </pre>
 */
class HandShakeTimeout : public ::omnetpp::cPacket
{
  protected:
    ::omnetpp::opp_string LCName;

  private:
    void copy(const HandShakeTimeout& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const HandShakeTimeout&);

  public:
    HandShakeTimeout(const char *name=nullptr, short kind=0);
    HandShakeTimeout(const HandShakeTimeout& other);
    virtual ~HandShakeTimeout();
    HandShakeTimeout& operator=(const HandShakeTimeout& other);
    virtual HandShakeTimeout *dup() const override {return new HandShakeTimeout(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getLCName() const;
    virtual void setLCName(const char * LCName);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const HandShakeTimeout& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, HandShakeTimeout& obj) {obj.parsimUnpack(b);}


#endif // ifndef __HANDSHAKETIMEOUT_M_H

