//
// Generated file, do not edit! Created by nedtool 5.4 from messages/HBResponse.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __HBRESPONSE_M_H
#define __HBRESPONSE_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "../common/Constants.h"
// }}

/**
 * Class generated from <tt>messages/HBResponse.msg:24</tt> by nedtool.
 * <pre>
 * packet HBResponse
 * {
 *     string displayString = DISPLAY_STR_MSG_HIDDEN;
 * 
 *     string sourceName;
 *     string destName;
 *     simtime_t timestamp;
 * }
 * </pre>
 */
class HBResponse : public ::omnetpp::cPacket
{
  protected:
    ::omnetpp::opp_string displayString;
    ::omnetpp::opp_string sourceName;
    ::omnetpp::opp_string destName;
    ::omnetpp::simtime_t timestamp;

  private:
    void copy(const HBResponse& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const HBResponse&);

  public:
    HBResponse(const char *name=nullptr, short kind=0);
    HBResponse(const HBResponse& other);
    virtual ~HBResponse();
    HBResponse& operator=(const HBResponse& other);
    virtual HBResponse *dup() const override {return new HBResponse(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getDisplayString() const;
    virtual void setDisplayString(const char * displayString);
    virtual const char * getSourceName() const;
    virtual void setSourceName(const char * sourceName);
    virtual const char * getDestName() const;
    virtual void setDestName(const char * destName);
    virtual ::omnetpp::simtime_t getTimestamp() const;
    virtual void setTimestamp(::omnetpp::simtime_t timestamp);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const HBResponse& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, HBResponse& obj) {obj.parsimUnpack(b);}


#endif // ifndef __HBRESPONSE_M_H

