//
// Generated file, do not edit! Created by nedtool 5.4 from messages/HBTimeout.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __HBTIMEOUT_M_H
#define __HBTIMEOUT_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>messages/HBTimeout.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet HBTimeout
 * {
 *     string hostName;
 *     simtime_t timeout;
 *     string hostAddr;
 * }
 * </pre>
 */
class HBTimeout : public ::omnetpp::cPacket
{
  protected:
    ::omnetpp::opp_string hostName;
    ::omnetpp::simtime_t timeout;
    ::omnetpp::opp_string hostAddr;

  private:
    void copy(const HBTimeout& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const HBTimeout&);

  public:
    HBTimeout(const char *name=nullptr, short kind=0);
    HBTimeout(const HBTimeout& other);
    virtual ~HBTimeout();
    HBTimeout& operator=(const HBTimeout& other);
    virtual HBTimeout *dup() const override {return new HBTimeout(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getHostName() const;
    virtual void setHostName(const char * hostName);
    virtual ::omnetpp::simtime_t getTimeout() const;
    virtual void setTimeout(::omnetpp::simtime_t timeout);
    virtual const char * getHostAddr() const;
    virtual void setHostAddr(const char * hostAddr);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const HBTimeout& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, HBTimeout& obj) {obj.parsimUnpack(b);}


#endif // ifndef __HBTIMEOUT_M_H

