//
// Generated file, do not edit! Created by nedtool 5.4 from messages/Termination.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __TERMINATION_M_H
#define __TERMINATION_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>messages/Termination.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet Termination
 * {
 *     string modulePath;
 * }
 * </pre>
 */
class Termination : public ::omnetpp::cPacket
{
  protected:
    ::omnetpp::opp_string modulePath;

  private:
    void copy(const Termination& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Termination&);

  public:
    Termination(const char *name=nullptr, short kind=0);
    Termination(const Termination& other);
    virtual ~Termination();
    Termination& operator=(const Termination& other);
    virtual Termination *dup() const override {return new Termination(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getModulePath() const;
    virtual void setModulePath(const char * modulePath);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Termination& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Termination& obj) {obj.parsimUnpack(b);}


#endif // ifndef __TERMINATION_M_H

