//
// Generated file, do not edit! Created by nedtool 5.4 from messages/Update.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __UPDATE_M_H
#define __UPDATE_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "../common/Constants.h"
// }}

/**
 * Class generated from <tt>messages/Update.msg:24</tt> by nedtool.
 * <pre>
 * packet Update
 * {
 *     string displayString = DISPLAY_STR_MSG_GROUP;
 * 
 *     // logical computer name
 *     string LCName;
 *     // event sender ID
 *     unsigned long senderId;
 *     // event sequence number
 *     int sequence;
 *     // update content
 *     string content;
 * 
 *     // sourceName and destName must be set for module purge
 *     string sourceName;
 *     string destName;
 * }
 * </pre>
 */
class Update : public ::omnetpp::cPacket
{
  protected:
    ::omnetpp::opp_string displayString;
    ::omnetpp::opp_string LCName;
    unsigned long senderId;
    int sequence;
    ::omnetpp::opp_string content;
    ::omnetpp::opp_string sourceName;
    ::omnetpp::opp_string destName;

  private:
    void copy(const Update& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Update&);

  public:
    Update(const char *name=nullptr, short kind=0);
    Update(const Update& other);
    virtual ~Update();
    Update& operator=(const Update& other);
    virtual Update *dup() const override {return new Update(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getDisplayString() const;
    virtual void setDisplayString(const char * displayString);
    virtual const char * getLCName() const;
    virtual void setLCName(const char * LCName);
    virtual unsigned long getSenderId() const;
    virtual void setSenderId(unsigned long senderId);
    virtual int getSequence() const;
    virtual void setSequence(int sequence);
    virtual const char * getContent() const;
    virtual void setContent(const char * content);
    virtual const char * getSourceName() const;
    virtual void setSourceName(const char * sourceName);
    virtual const char * getDestName() const;
    virtual void setDestName(const char * destName);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Update& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Update& obj) {obj.parsimUnpack(b);}


#endif // ifndef __UPDATE_M_H

